### PR TITLE
Display seconds since game began

### PR DESCRIPTION
**Pull request by robertkarl**
- Serialize and send game start time to clients
- Show seconds since then in big font
# future stuff

Send down a "game over message" and stop the timer
# Test Plan

Opened two clients: they display the same time.

### CODE REVIEW

**Comment by robertkarl** [comment]
screen shot 2015-09-02 at 10 09 43 pm

**Comment by zackgomez** [comment]
What do you think about putting this in the Game V0 component?

I guess this is actually pretty good in the Game component.  Eventually the Game object will become the 'Engine' object and a new object called the 'Map' or 'Level' would replace some of this.  This property would be in the Level then.  Or in the Engine as 'levelStartTime'

**Comment by zackgomez** [comment]
Anyways, i think this is good for now, except that it should start when the first player joins.

**Comment by zackgomez** [comment]
I committed 6a2b4cfc0b6cdb1db8e210fb8d1656c6a529b1ed which creates games when a player joins, solving the blocking issue.  So I merged this.

**Comment by zackgomez** [comment]
I verified that starting a game starts the timer over again.

**Pull request merged**
